### ISSUE TITLE
[1.8.9] NoClassDefFoundError when running as a dedicated server 

### ISSUE THREAD

**Issue by cauliflower69** [joekaiser/practicalities#49] opened 2016-01-12 10:54 UTC
http://pastebin.com/C6KbSBPh

All the other mods seem to behave properly until this is added then it crashes

**Comment by joekaiser** [comment] 2016-01-12 16:25
```
net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: practicalities/items/ItemMagnet
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:559)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
   at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:112)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by joekaiser** [comment] 2016-01-12 16:27
Duplicate of #47 Closing this one and I will track against the other one.

**Closed as completed by joekaiser** 2016-01-12 16:27 UTC
Labels: bug

**Comment by joekaiser** [comment] 2016-01-12 19:45
The cause is a derp I made. Each Item `implements ItemMeshDefinition`, which of course isn't on the server instance. Gotta refactor a lot

**Comment by cauliflower69** [comment] 2016-01-12 19:53
Glad you found the error
